"""Add prestataire_id to Reservation

Revision ID: 3a18ac8cce96
Revises: 92cc2309772b
Create Date: 2025-07-22 16:02:38.294962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a18ac8cce96'
down_revision = '92cc2309772b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prestataire_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_reservation_prestataire_id_user", 'user', ['prestataire_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('prestataire_id')

    # ### end Alembic commands ###
