"""Add Service model

Revision ID: 4e163369b876
Revises: f093c719ee30
Create Date: 2025-07-21 19:42:49.961739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e163369b876'
down_revision = 'f093c719ee30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('categorie', sa.String(length=50), nullable=False),
    sa.Column('localisation', sa.String(length=100), nullable=False),
    sa.Column('prestataire_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prestataire_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service')
    # ### end Alembic commands ###
