"""Add Service model

Revision ID: 80d4bc5dfb50
Revises: 4e163369b876
Create Date: 2025-07-21 20:07:56.656770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d4bc5dfb50'
down_revision = '4e163369b876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('competences', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('disponibilite', sa.Boolean(), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('disponibilite')
        batch_op.drop_column('competences')
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
