"""fixed naming error

Revision ID: 956883fe8777
Revises: 3a18ac8cce96
Create Date: 2025-07-22 16:47:51.138957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956883fe8777'
down_revision = '3a18ac8cce96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_reservation')
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prestataire_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_reservation_provider_id_user'), type_='foreignkey')
        batch_op.create_foreign_key("fk_reservation_provider_id_user", 'user', ['prestataire_id'], ['id'])
        batch_op.drop_column('provider_id')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('provider_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['provider_id'], ['id'])

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reservation_provider_id_user'), 'user', ['provider_id'], ['id'])
        batch_op.drop_column('prestataire_id')

    op.create_table('_alembic_tmp_reservation',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('prestataire_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('client_id', sa.INTEGER(), nullable=False),
    sa.Column('service_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['prestataire_id'], ['user.id'], name=op.f('fk_reservation_provider_id_user')),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
